version: '3.8' 
  services:
    web:
      depends: 
        - postgres_db

    postgres_db:
      image: postgres:latest
      expose:
        - 5432
      environment:
        - POSTGRES_USER=volunteer_village
        - POSTGRES_PASSWORD=volunteer_village123
        - POSTGRES_DB=village 
  volumes:
    postgres_db: /var/lib/postgresql/data/
