version: '3'

services:
  web:
    build: .
    ports:
      - "443:443"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name
